### ISSUE TITLE
`^id [r b g] wisdomkings [-trailo -kunda]` throws an error

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#1774]
```
Traceback (most recent call last):
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 1232, in invoke
    await ctx.command.invoke(ctx)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/core.py", line 931, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/core.py", line 196, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ZeroDivisionError: division by zero
```

LOL WHAT

**Comment by RheingoldRiver** [comment]
![image](https://user-images.githubusercontent.com/18037011/178130601-37f8f82b-d9f0-4a56-86d6-0f06a6c573c7.png)
