### ISSUE TITLE
id1 is throwing an error when there's no result 

### ISSUE THREAD

**Issue by RheingoldRiver** [TsubakiBotPad/pad-cogs#727]
Try: `^id1 base 6871`

```
Traceback (most recent call last):
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/bot/tsubaki/prod/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'is_low_priority'
```

**Comment by RheingoldRiver** [comment]
So turns out id1 flips out when it can't distinguish between 2 cards, such as the 2 forms of Miada. We're no longer developing for id1 so this is a wontfix but we are wrapping in a try-catch with an error message explaining to use id3 for the query.
